## Required ##

# A discord token for the bot to login
discord_token = 'Your token'

# Where the invite should be created (run when app gets created and is logged with the INFO level)
workshop_invite_channel = 877

# Per guild configuration
[guilds.123]
# FROM where TO where should users be automatically moved
automove_from = 852
automove_to = 159
