## Required ##

# A discord token for the bot to login
DISCORD_TOKEN = 'Your token'

## Optional ##
# Where the invite should be created (run when app gets created and is logged with the INFO level)
WORKSHOP_INVITE_CHANNEL = "123"
# FROM where TO where should users be automatically moved
WORKSHOP_AUTOMOVE_FROM = "456"
WORKSHOP_AUTOMOVE_TO = "789"
