name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker images
        run: DOCKER_BUILDKIT=1 docker build . -t ghcr.io/ssps-kb/workshop-bot:latest
      - name: Deploy the Docker images
        run: DOCKER_BUILDKIT=1 docker push ghcr.io/ssps-kb/workshop-bot:latest